sudo: required
services:
  - docker
after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t bablot/app /app
  - docker build -t bablot/nginx /nginx
  - docker build -t bablot/postgres /postgres
  - docker push bablot/app
  - docker push bablot/nginx
  - docker push bablot/postgres
branches:
  only:
    - master
    - travis
