version: '2'
services:
  app:
    links:
      - pg
      - rabbitmq:amq
    environment:
      - PGHOST=pg
      - PGDATABASE=postgres
      - PGUSER=postgres

  nginx:
    links:
      - app:node
    ports:
      - "9000:9000"

  pg:
    ports:
      - "5432:5432"

  chindow:
    image: bablot/chindow

  chatterpillar:

  rabbitmq:
    image: rabbitmq:3
    ports:
      - "5672:5672"

