node:
  build: .
  ports:
    - "8080:8080"
  volumes:
    - ./app:/usr/src/app
    # - /usr/src/app/node_modules
  links:
    - pg
    - rabbitmq:amq
  environment:
    - PGHOST=pg
    - PGDATABASE=postgres
    - PGUSER=postgres

nginx:
  build: ./nginx
  links:
    - node:node
  ports:
    - "80:80"
    - "443:443"
pg:
  build: ./postgres
  ports:
    - "5432:5432"
rabbitmq:
  image: rabbitmq:3
  ports:
    - "15672:15672"

# SERVICES
chindow:
  image: dharness/chindow
  ports:
    - "9999:9999"
  links:
    - rabbitmq:amq
