version: '2'
services:
  app:
    image: bablot/app
    environment:
      MONGO_URI: 'mongodb://sirblabsalot:bluecakes@ds061984.mlab.com:61984/bablot'
    command: npm start

  chatterpillar:
    image: bablot/chatterpillar
    command: npm start

  nginx:
    image: bablot/nginx

