version: '2'
services:
  app:
    image: bablot/app
    environment:
      BABLOT_API_URL: 'https://162.243.218.96:9000'
      MONGO_URI: 'mongodb://sirblabsalot:bluecakes@ds061984.mlab.com:61984/bablot'
    command: npm start

  chatterpillar:
    image: bablot/chatterpillar
    command: npm start

  nginx:
    image: bablot/nginx

