version: '2'
services:
  app:
    build: ./app
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      MONGO_URI: 'mongodb://sirblabsalot:bluecakes@ds051625.mlab.com:51625/dev_bablot'

  nginx:
    build: ./nginx

  pg:
    build: ./postgres

  chatbot:
    build: ./chatbot
    volumes:
      - ./chatbot:/usr/src/chatbot
      - /usr/src/chatbot/node_modules
    command: npm run dev

