version: '2'
services:
  app:
    ports:
      - "8080:8080"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - pg
      - rabbitmq:amq
    environment:
      - PGHOST=pg
      - PGDATABASE=postgres
      - PGUSER=postgres

  nginx:
    links:
      - app:node
    ports:
      - "80:80"
      - "443:443"

  pg:
    ports:
      - "5432:5432"

  chindow:
    image: bablot/chindow
    ports:
      - "9999:9999"

  rabbitmq:
    image: rabbitmq:3
    ports:
      - "5672:5672"
      - "15672:15672"

