version: '2'
services:
  app:
    build: ./app
    volumes:
      - ./protos:/usr/src/app/protos
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      MONGO_URI: 'mongodb://sirblabsalot:bluecakes@ds051625.mlab.com:51625/dev_bablot'
    command: npm run dev

  chatterpillar:
    build: ./chatterpillar
    volumes:
      - ./protos:/usr/src/app/protos
      - ./chatterpillar/src:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  nginx:
    build: ./nginx
    volumes:
      - ./nginx:/etc/nginx/


